<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LeagueScreenAnalyzer.Core\LeagueScreenAnalyzer.Core.csproj" />
    <ProjectReference Include="..\LeagueScreenAnalyzer.Capture\LeagueScreenAnalyzer.Capture.csproj" />
    <ProjectReference Include="..\LeagueScreenAnalyzer.Imaging\LeagueScreenAnalyzer.Imaging.csproj" />
    <ProjectReference Include="..\LeagueScreenAnalyzer.Storage\LeagueScreenAnalyzer.Storage.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
